load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library", "cc_test")


cc_library(
  name = "threadpool",
  srcs = [
    "threadpool.cc",
  ],
  hdrs = [
    "threadpool.hpp",
  ],
  includes = [
    ".",
  ],
  visibility = [
    "//visibility:public"
  ]
)