load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library", "cc_test")


cc_library(
  name = "locker",
  srcs = [
  ],
  hdrs = [
    'rwmutex.hpp'
  ],
  includes = [
    '.'
  ],
  visibility = [
    "//visibility:public",
  ]
)